const Civil_details = {
  description1: `The Civil Engineering Department at Puducherry Technological University (PTU) has positioned itself as a vanguard in both environmental sustainability and geotechnical advancements within the civil engineering domain. The department's dual focus not only on cutting-edge materials and sustainable practices but also on the intricate understanding and improvement of geotechnical properties underscores its comprehensive approach towards addressing contemporary challenges in construction and environmental stewardship. In geotechnical engineering, PTU has embarked on pioneering research aimed at enhancing ground improvement techniques and soil stabilization methods. This includes leveraging calcined clay for construction purposes, a practice that has garnered the department numerous international accolades. By focusing on the utilization of calcined clay, the department is contributing to more sustainable construction methodologies, reducing the environmental impact of construction projects, and improving the durability and stability of infrastructure. These efforts are instrumental in paving the way for more efficient, cost-effective, and environmentally friendly construction practices that can be adopted worldwide. One of the key research areas of the department is the development of biohydrogen as part of the green energy drive, moving from laboratory prototypes to commercialization. This involves collaboration among students, scholars, and startups, highlighting the role of technology transfer in promoting sustainable energy solutions.`,
  description2: `By focusing on biohydrogen, PTU is actively contributing to reducing reliance on fossil fuels and minimizing carbon emissions, showcasing its commitment to energy sustainability. The department's exploration into innovative materials includes the development of textile-reinforced concrete (TRC) panels, where traditional steel reinforcement is replaced with non-corrosive mesh reinforcement. This innovation not only leads to a reduction in the concrete material requirement by up to 85% but also extends the application of concrete to new domains, such as aerospace and architecture, due to improved structural and thermal performance. Furthering its commitment to sustainable construction practices, PTU is investigating the use of pervious concrete as a sustainable pavement material, which plays a significant role in storm water management and groundwater recharge. Additionally, the research on alternate materials for aggregates, focusing on recycled waste plastics and crushed glass cullets, addresses the critical issue of natural aggregate scarcity and non-biodegradable waste accumulation. Moreover, the utilization of marine brown algae extract as a natural polymer in construction materials highlights the department's endeavor towards eco-friendly building solutions. This, along with the enhancement of fiber-reinforced concrete beams with GFRP composites, demonstrates PTU's innovative approach to overcoming traditional construction challenges, such as corrosion and maintenance in steel-reinforced structures.`,
  description3: `The Civil Engineering Department at Puducherry Technological University is thus making significant strides in both environmental sustainability and geotechnical engineering. Its comprehensive research initiatives are not only advancing the knowledge base in these areas but also offering practical solutions that have the potential to revolutionize the construction industry and contribute to a more sustainable future.`,
  materialTesting1: [
    `Universal Testing Machine (Utm)`,
    `Computerized Tensile Testing Machine (Ttm) 5 Kn`,
    `Impact Testing Machine`,
    `Erichsen-Cuping Testing Machine  – 20 Model`,
    `Hardness Testing Machine`,
    `Torsion Testing Machine`,
    `Universal Wood Testing Machine Proving Ring Of Capacity `,
    `Electronic Spring Testing Machine`,
  ],
  materialTesting2: [
    `Determination Of Specific Gravity Of Cement`,
    `Determination Of Standard Consistency Of Cement`,
    `Determination Of Initial And Final Setting Times Of Cement`,
    `Determination Of Compressive Strength Of Cement Mortar.`,
    `Determination Of Specific  Gravity And Water Absorption Of Fine & Coarse Aggregates`,
    `Determination Of Fineness Modulus Of Fine Aggregat & Coarse Aggregate`,
    `Determination Of  Degree Of Workability: Slump Cone Test, Demo Test`,
    `Determination Of Compressive Strength Of Concrete`,
    `Determination Of Flexural Strength Of Concrete`,
    `Determination Of Splitting Tensilte Strength Of Concrete`,
    `CBR Test On The Soil/Granular Material`,
    `Crushing Value Tst, Impact Value Test, And Angularity Test On Aggregates`,
    `Pentration Test And Softening Point Test`,
    `Flash Point Test And Viscosity Test`,
  ],
  concreteLab: [
    `Compression testing machine – 3000 kN capacity`,
    `Automatic compression testing  machine – 2000 kN capacity`,
    `Concrete & mortar  vibration machines`,
    `Flow table for mortar and concrete`,
    `Tile abrasion testing machine`,
    `Accelerated curing bath`,
    `Concrete pam mixer`,
    `Load frame – (300 kN capacity) along with data logger for load displacement and strain`,
    `Electric box furnace – 1100 c Capacity `,
    `Autoclave`,
    `Bail mill`,
    `Thermal conductivity apparatus`,
    `Jaw crushes`,
    `Hot air oven`,
    `Automatic Blaine apparatus – to test fineness of powder materials`,
    `Jolting apparatus`,
    `Sieve shaker`,
    `Flexure testing machine – 50KN`,
    `Loading frame for Beam – 300 kN`,
    `Loading frame for column – 2000 kN `,
    `NDT equipment`,
    `Aggregate Crushes`,
    `Concrete Abrasions Testing In Wet Condition`,
    `Three Permeability Test On Crete`,
  ],
  important: [
    `All physical tests on cements and concrete as stipulated by the relevant BIS`,
    `All physical tests on fine and coarse aggregate`,
    `Tests on hardened concrete – Compressive strength, split tensile strength, flexure tensile strength – Accelerated curing test`,
    `NDT – Estimation of probable strength of concrete, concrete quality and homogeneity, condition of rebar, concrete cover, diameter of existing rebar, etc.`,
    `Tests on bricks as per relevant BIS`,
    `Tests on tiles – Mosaic tiles, clay tiles, ceramic tiles, citified tiles, paver blocks, hollow blocks, etc`,
    `Load – deflection of flexural members`,
    `Load – deflection of flexural members Beam column joint`,
    `Mix proportioning of Concrete mixtures`,
  ],
  geotechnical: [
    `Grain Size Distribution Is:2720 (Part Iv)-1985`,
    `Liquid Limit & Plastic Limit Is:2720 (Part V)-1985`,
    `Shrinkage Limit Is:2720 (Part Vi)-1972`,
    `Visual Classification Of Soil Is: 1498-1972`,
    `Hydrometer Analysis Is:2720(Part  Iii/Sec 3) -1980`,
    `Permeability Test Is:2720(Partxvii)-1986 Proctor Compaction Test Is:2720(Part Vii)-1980`,
    `Unconfined Compression Test Is:2720(Part X)-1986`,
    `Direct Shear Test Is:2720 (Part Xiii)-1986`,
    `Triaxal Test Is:2720(Part Xi)-1991`,
    `Field Density Is:2720 (Part Ix)-1992`,
    `Water Content – Gravimetric Method`,
    `Specific Gravity – Pycnometer And Density Bottle`,
    `Partial Size Distribution – Mechanical Sand Equivalent`,
    `Hydrometer`,
    `Atterberg Limit Apparatus`,
    `Direct Shear Test Apparatus`,
    `Ordinary Triaxial Apparatus`,
    `Unconfined Compression Strength (Ucs) Test Apparatus`,
    `Consolidation Apparatus`,
    `Permeability Of Soil`,
    `Sand Replacement Apparatus`,
    `Core Cutter Apparatus`,
    `Soil Extractor (Horizontal & Vertical Apparatus)`,
  ],
  surveylab: [
    `TOTAL STATION : 1” accuracy with software and other surveying equipment and accessories`,
    `Hand held GPS SERVICES OFFERED`,
    `Land and Road Surveying`,
    `Setting up of boundaries`,
    `Developing contours and traversing`,
    `Setting up R.L. for embankments and alignment of roads`,
    `Marking boundaries  with respect to the cadastral maps (secondary triangulation)`,
  ],
  environmentalLab: [
    `UV – visible spectrophotometry`,
    `Atomic  Absorption Spectrophotometer (AAS)`,
    `Gas Chromato graph`,
    `TOC – HACH meter`,
    `COD reactor`,
    `Humidifier`,
    `Flame photometer`,
    `Water and Wastewater testing facilities`,
    `BoD INCUBATOR DEEP Freezer Microbial Hood`,
  ],
  majorEquipments: [
    `Water quality testing`,
    `Waste water quality testing`,
    `Lime analysis`,
    `Physical – chemical parameter of solid / sludge`,
    `Metal analysis`,
    `Nutrient analysis`,
    `Air sampling`,
    `Testing of gaseous pollutants`,
    `Solid waste sampling and testing`,
    `Toxicity limits in water, soil and air`,
    `Biomass / Microbial blomass`,
    `Microscopic Examinator`,
  ],
};

export { Civil_details };
